Decorate
andym80/oop-school-library pull request #2
Opened 2022-11-01 20:58 UTC by andym80

## **GOOD REVIEWER**
l used the Decorator design pattern to correct the names of people and following the changes required, I could implement these.

2022-11-01 21:09 UTC, MahmoudBakr23 reviewed
### Hi @andym80 😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

## **Invalid Submission**

- Please add a README file, use this [template](https://github.com/microverseinc/readme-template) 😄 

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._ 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

2022-11-01 22:29 UTC, BenMukebo requested changes
### Hi @andym80,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Good commit messages ✔️ 
- Professional README ✔️
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 22:29 UTC, BenMukebo commented on nameable.rb
> +end
- [OPTIONAL] 🤔 What if you add this text to the correct_name method of the Namable class 👇🏻 
```ruby
   raise NotImplementedError, "#{self.class} has not implemented method '#{__method__}'"
```

2022-11-01 22:29 UTC, BenMukebo commented on person.rb
> +puts capitalized_trimmed_person.correct_name
- [ ] Great job so far 👍🏻 however your logic does not work correctly instead I'm getting `Unknown` in my console

![Screenshot from 2022-11-02 00-12-03](https://user-images.githubusercontent.com/79058364/199352298-deb173e3-19d8-43ee-aece-6fdf18cf685c.png)

2022-11-02 01:40 UTC, gemmen29 approved these changes
Hi @andym80, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 01:43 UTC, merged